source-file $HOME/.tmux/config.d/terminal.conf
source-file $HOME/.tmux/config.d/core.conf

unbind C-b
set -g prefix C-Space

unbind r
bind r source-file ~/.tmux.conf \; display "tmux.conf reloaded"

source-file $HOME/.tmux/config.d/copy-mode.conf
source-file $HOME/.tmux/config.d/btop-popup.conf
source-file $HOME/.tmux/config.d/lazygit-popup.conf
source-file $HOME/.tmux/config.d/status-bar.conf

# default plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# plugin modules
set -g @plugin 'dracula/tmux'
source-file $HOME/.tmux/plugins.d/dracula.conf

set -g @plugin 'erlenmeyer316/tmux-tilish' 
source-file $HOME/.tmux/plugins.d/tmux-tilish.conf



# Install 'tpm' if needed
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialiize tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'
