bind s display-popup -E \
  "tmux list-panes -s \
    -F '#{window_index}.#{pane_index}  #{pane_current_command}  #{pane_title}' \
  | fzf --reverse \
  | awk '{print \$1}' \
  | xargs -r tmux select-pane -t"