set -g @dracula-colors " white='#f8f8f2' gray='#44475a' dark_gray='#282a36' light_purple='#bd93f9' dark_purple='#6272a4' cyan='#8be9fd' green='#50fa7b' orange='#ffb86c' red='#ff5555' pink='#ff79c6' yellow='#f1fa8c' "

set -g @dracula-plugins "uptime cpu-usage ram-usage time battery"
set -g @dracula-battery-label false
set -g @dracula-show-battery-status true
set -g @dracula-no-battery-label " "
set -g @dracula-cpu-display-load true
set -g @dracula-cpu-usage-label " "
set -g @dracula-ram-usage-label " "
set -g @dracula-uptime-label "󱎫 "
# per default available colors: white, gray, dark_gray, light_purple, dark_purple, cyan, green, orange, red, pink, yellow
# set -g @dracula-[plugin-name]-colors "[background] [foreground]"
