# Terminal & Color
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"             # true color for capable term
set -ga terminal-overrides ",st-256colors:Tc"  # explicit Tc for st

# core behavior
set -s escape-time 0
set -g base-index 1
set -g history-limit 100000
set -g focus-events on
set -g set-clipboard on

# prefix
unbind C-b
set -g prefix C-Space

# misc bind
unbind r
bind r source-file ~/.tmux.conf \; display "tmux.conf reloaded"

#bind q confirm-before -p "Kill pane? (y/n)" kill-pane
#bind Q confirm-before -p "Kill window? (y/n)" kill-window

# Pane resize -- -r makes the bind repeatable without re-pressing prefix
bind -r H resize-pane -L 3
bind -r J resize-pane -D 3
bind -r K resize-pane -U 3
bind -r L resize-pane -R 3

# quick popup for lazygit - opens over current pane, q closes it
bind g display-popup -E -w 90% -h 90% "lazygit"

# fzf session switcher
#bind s display-popup -E "tmux list-sessions | fzf --reverse | cut -d: -f1 | xargs tmux switch-client -t"

# copy mode (vi)
set -g mode-keys vi

unbind [
unbind ]
bind c copy-mode

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel"
unbind p
bind p paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xsel"

# status bar
set -g status on
set -g status-position top
set -g status-interval 5     # refresh every 5s


# List of plugins.
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# theme
set -g @plugin 'dracula/tmux'
set -g @dracula-colors " white='#f8f8f2' gray='#44475a' dark_gray='#282a36' light_purple='#bd93f9' dark_purple='#6272a4' cyan='#8be9fd' green='#50fa7b' orange='#ffb86c' red='#ff5555' pink='#ff79c6' yellow='#f1fa8c' "

set -g @dracula-plugins "uptime cpu-usage ram-usage time battery"
set -g @dracula-battery-label false
set -g @dracula-show-battery-status true
set -g @dracula-no-battery-label " "
set -g @dracula-cpu-display-load true
set -g @dracula-cpu-usage-label " "
set -g @dracula-ram-usage-label " "
set -g @dracula-uptime-label "󱎫 "
# per default available colors: white, gray, dark_gray, light_purple, dark_purple, cyan, green, orange, red, pink, yellow
# set -g @dracula-[plugin-name]-colors "[background] [foreground]"

# Configure tmux-tilish
set -g @plugin 'erlenmeyer316/tmux-tilish' 
set -g @tilish-default 'main-vertical'
set -g @tilish-dmenu 'on'

# Install 'tpm' if needed
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialiize tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'
